openapi: 3.0.2
info:
  contact:
    email: support@allocatesoftware.com
    name: API support
    url: http://www.allocatesoftware.com/
  description: |2

        ## API and events for providing workers.
  title: Worker API and Events
  version: 1.0.0
  x-logo:
    url: http://www.allocatesoftware.com/wp-content/uploads/sites/31/2017/08/Allocate_logo_digital_Horizontal_RGB_retina.png
    backgroundColor: '#FFFFc0'
    altText: Allocate Software
servers:
- url: http://healthsuite.allocatesoftware.com/api/v1
security:
- jwt: []
tags:
- name: Worker
paths:
  /workers:
    post:
      description: "Provide worker details for inclusion into the Allocate ecosystem.\
        \ \nThe platform will accept the worker information, and respond either synchronously\
        \ or asynchronously with the allocate worker identifier. \nThis may entail\
        \ an on-boarding process, so the final response may require human interaction\
        \ before it can be completed.\n\nWhere there is a source system in common,\
        \ such as HealthSuite and a Bank system both using ESR as a source of worker\
        \ data, a person record\ncontaining an ESR trust-relative Staff Number is\
        \ likely to be sufficient.\n"
      operationId: register_worker
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Person'
        description: Worker information
        required: true
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkerRegistrationResponse'
          description: The worker has been registered successfully
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: One or more errors have occurred when attempting to process
            the provided data
        403:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Forbidden - you do not have the necessary permissions to undertake
            this action
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncResponse'
          description: The worker data has been accepted, and will be processed in
            due course.
      x-openapi-router-controller: api_server.controllers.default_controller
  /workers/{id}:
    get:
      description: "Retrieve worker details from the Allocate ecosystem using the\
        \ Allocate Worker id.\nThe Allocate Worker id will be issued when registering\
        \ a worker. \n"
      operationId: get_worker
      parameters:
      - description: The ID of the worker
        example: 2CBC7FF9-38FB-4F0A-835A-324D9CF4800C
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
          description: Worker successfully found
        404:
          description: The worker was not found
        403:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Forbidden - you do not have the necessary permissions to undertake
            this action
      x-openapi-router-controller: api_server.controllers.default_controller
  /workers/{id}/onboardToTrust:
    post:
      description: "On-board a worker to a particular trust. In scenarios where worker\
        \ data is being provided by a 3rd party Human Resources (or equivalent) system,\
        \ it may be necessary to 'on-board' that worker into a particular trust so\
        \ that they may be selected.\nNote that in external bank scenarios this is\
        \ not required, since the trust on-boarding request is implicit within the\
        \ worker offer. \n"
      operationId: onboard_worker_to_trust
      parameters:
      - description: The Allocate Worker ID
        example: EB7659C5-6AD3-4C1F-8F3F-A5DB1A5E1440
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        $ref: '#/components/requestBodies/inline_object'
        content:
          application/json:
            schema:
              properties:
                trustCode:
                  description: The code for the trust that the worker should be on-boarded
                    to
                  type: string
                engagementRoute:
                  description: The 'engagement route' of the worker, such as substantive,
                    bank, agency
                  type: string
              type: object
        description: Worker information
        required: true
      responses:
        200:
          description: The worker has been on-boarded successfully
        400:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: One or more errors have occurred when attempting to process
            the provided data
        403:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Forbidden - you do not have the necessary permissions to undertake
            this action
        202:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AsyncResponse'
          description: The request has been accepted, and will be processed in due
            course.
      tags:
      - Worker
      x-openapi-router-controller: api_server.controllers.worker_controller
components:
  requestBodies:
    inline_object:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_object'
      required: true
  schemas:
    AsyncResponse:
      description: "Where an API may respond with an asynchronous 'Accepted' (HTTP\
        \ 202) response, it will return an AsyncResponse object. The eventual\n  \
        \              response will be returned by way of an async event, containing\
        \ the corresponding correlation ID header returned below.\n              \
        \  \n                The location of the correlation ID will depend upon the\
        \ eventing transport in use - though typically it will be included as a message\
        \ header (rather than a payload).\n            "
      properties:
        id:
          description: Correlation Identifier
          example: 8FE4E2F3-7351-4385-B0C6-1154A440F956
          type: string
      required:
      - id
      type: object
    DateSpan:
      example:
        from: 2000-01-23T04:56:07.000+00:00
        to: 2000-01-23T04:56:07.000+00:00
      properties:
        from:
          description: When the span starts
          format: date-time
          type: string
        to:
          description: When the span ends
          format: date-time
          type: string
      required:
      - from
      type: object
    TimeSpan:
      description: Represents a span of time, implicitly covering a maximum of 24hrs
      example:
        from: 01:00
        to: 08:30
      properties:
        from:
          description: Time from, 24hr format
          example: 01:00
          pattern: ^(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$
          type: string
        to:
          description: Time from, 24hr format
          example: 08:30
          pattern: ^(0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$
          type: string
      required:
      - from
      type: object
    ErrorResponse:
      description: An Error has occurred in processing your request
      properties:
        id:
          description: Optional identifier for this reponse (for matching with logging)
          type: string
        code:
          description: Optional error code identifying this particular error
          type: string
        description:
          description: Optional error code identifying this particular error
          type: string
        items:
          description: List of child errors
          items:
            $ref: '#/components/schemas/ErrorResponse'
          type: array
      required:
      - description
      type: object
    Identifier:
      description: Flexible identifier
      example:
        namespace: NI
        id: QQ123456C
      properties:
        namespace:
          description: Namespace for this identifier.
          example: NI
          type: string
        id:
          example: QQ123456C
          type: string
      required:
      - id
      - namespace
      type: object
    Person:
      example:
        personalInfo:
          additionalID: additionalID
          placeOfBirth: placeOfBirth
          nationality: nationality
          visaRequired: visaRequired
          disability: disability
          maidenName: maidenName
          ethnicOrigin: ethnicOrigin
          disabledNo: disabledNo
          maritalStatus: maritalStatus
        workLocations:
          homeTrust: homeTrust
          workingTrusts:
          - ""
          - ""
        visas:
        - number: number
          country: country
          entries: entries
          issuingOffice: issuingOffice
          validity:
            from: 2000-01-23T04:56:07.000+00:00
            to: 2000-01-23T04:56:07.000+00:00
          type: type
        - number: number
          country: country
          entries: entries
          issuingOffice: issuingOffice
          validity:
            from: 2000-01-23T04:56:07.000+00:00
            to: 2000-01-23T04:56:07.000+00:00
          type: type
        availabilities:
          Availability:
          - '{}'
          - '{}'
          NoBank:
          - '{}'
          - '{}'
        employmentDetails:
          employeeType: employeeType
          dateJoinedNHS: dateJoinedNHS
          hireDetails: hireDetails
          agencies: agencies
          employmentStatus: employmentStatus
          prevEmployer: prevEmployer
          alAccrualPlan: alAccrualPlan
        personalPattern:
          duty:
          - '{}'
          - '{}'
          unavailability:
          - '{}'
          - '{}'
        contracts:
        - wtdOptOut: true
          salaryAmount: 0.8008281904610115
          staffGroup: staffGroup
          contractType: contractType
          salaryFrequency: salaryFrequency
          grade: grade
          contract: contract
          contractedTime: contractedTime
          defaultUnavailabilityHours: defaultUnavailabilityHours
          payscale: payscale
        - wtdOptOut: true
          salaryAmount: 0.8008281904610115
          staffGroup: staffGroup
          contractType: contractType
          salaryFrequency: salaryFrequency
          grade: grade
          contract: contract
          contractedTime: contractedTime
          defaultUnavailabilityHours: defaultUnavailabilityHours
          payscale: payscale
        skills:
        - skillGroup: skillGroup
          dateGained: dateGained
          cluster: cluster
          notes: notes
          obtainedFromReason: obtainedFromReason
          certificateNumber: certificateNumber
          skill: skill
          validity:
            from: 2000-01-23T04:56:07.000+00:00
            to: 2000-01-23T04:56:07.000+00:00
        - skillGroup: skillGroup
          dateGained: dateGained
          cluster: cluster
          notes: notes
          obtainedFromReason: obtainedFromReason
          certificateNumber: certificateNumber
          skill: skill
          validity:
            from: 2000-01-23T04:56:07.000+00:00
            to: 2000-01-23T04:56:07.000+00:00
        specialties:
        - notes: notes
          validity:
            from: 2000-01-23T04:56:07.000+00:00
            to: 2000-01-23T04:56:07.000+00:00
          tempStaffSpeciality: tempStaffSpeciality
        - notes: notes
          validity:
            from: 2000-01-23T04:56:07.000+00:00
            to: 2000-01-23T04:56:07.000+00:00
          tempStaffSpeciality: tempStaffSpeciality
        identification:
          middleInitials: middleInitials
          gender: male
          surname: Smith
          knownAs: knownAs
          dateOfBirth: 2000-01-23
          title: Mr
          forenames: '[''Fred'',''Jim'']'
        workingRestrictions:
        - hoursOfWork:
            thu:
              from: 01:00
              to: 08:30
            tue:
              from: 01:00
              to: 08:30
            wed:
              from: 01:00
              to: 08:30
            sat:
              from: 01:00
              to: 08:30
            fri:
              from: 01:00
              to: 08:30
            mon:
              from: 01:00
              to: 08:30
            sun:
              from: 01:00
              to: 08:30
          restrictions:
            maxConsecutiveDaysRequested: maxConsecutiveDaysRequested
            maxOvertimePerWeek: maxOvertimePerWeek
            minBreakBetweenShifts: 6.027456183070403
            notes: notes
            wtdWeekTimeStart: wtdWeekTimeStart
            additionalHoursPerWeek: additionalHoursPerWeek
            maxConsecutiveDays: maxConsecutiveDays
            maxOvertimePerDay: maxOvertimePerDay
            wtdWeekDayStart: wtdWeekDayStart
            maxShiftsPerWeek: maxShiftsPerWeek
            wtdDayStart: wtdDayStart
            maxDurationPerShift: maxDurationPerShift
            maxOvertimePerCalendarMonth: maxOvertimePerCalendarMonth
            effectiveFrom: effectiveFrom
            maxWorkTimePerDay: maxWorkTimePerDay
            daysPerWeek: daysPerWeek
            maxDaysPerWeek: maxDaysPerWeek
          validity:
            from: 2000-01-23T04:56:07.000+00:00
            to: 2000-01-23T04:56:07.000+00:00
          title: title
          defaultLeaveHours:
            fridayTime: fridayTime
            useWorkingDay: useWorkingDay
            tuesdayTime: tuesdayTime
            mondayTime: mondayTime
            sundayTime: sundayTime
            saturdayTime: saturdayTime
            wednesdayTime: wednesdayTime
        - hoursOfWork:
            thu:
              from: 01:00
              to: 08:30
            tue:
              from: 01:00
              to: 08:30
            wed:
              from: 01:00
              to: 08:30
            sat:
              from: 01:00
              to: 08:30
            fri:
              from: 01:00
              to: 08:30
            mon:
              from: 01:00
              to: 08:30
            sun:
              from: 01:00
              to: 08:30
          restrictions:
            maxConsecutiveDaysRequested: maxConsecutiveDaysRequested
            maxOvertimePerWeek: maxOvertimePerWeek
            minBreakBetweenShifts: 6.027456183070403
            notes: notes
            wtdWeekTimeStart: wtdWeekTimeStart
            additionalHoursPerWeek: additionalHoursPerWeek
            maxConsecutiveDays: maxConsecutiveDays
            maxOvertimePerDay: maxOvertimePerDay
            wtdWeekDayStart: wtdWeekDayStart
            maxShiftsPerWeek: maxShiftsPerWeek
            wtdDayStart: wtdDayStart
            maxDurationPerShift: maxDurationPerShift
            maxOvertimePerCalendarMonth: maxOvertimePerCalendarMonth
            effectiveFrom: effectiveFrom
            maxWorkTimePerDay: maxWorkTimePerDay
            daysPerWeek: daysPerWeek
            maxDaysPerWeek: maxDaysPerWeek
          validity:
            from: 2000-01-23T04:56:07.000+00:00
            to: 2000-01-23T04:56:07.000+00:00
          title: title
          defaultLeaveHours:
            fridayTime: fridayTime
            useWorkingDay: useWorkingDay
            tuesdayTime: tuesdayTime
            mondayTime: mondayTime
            sundayTime: sundayTime
            saturdayTime: saturdayTime
            wednesdayTime: wednesdayTime
        ids:
        - namespace: NI
          id: QQ123456C
        - namespace: NI
          id: QQ123456C
        postings:
        - unit: unit
          post: post
          isPrimary: true
          team: team
          assignmentNumber: assignmentNumber
          postingType: postingType
        - unit: unit
          post: post
          isPrimary: true
          team: team
          assignmentNumber: assignmentNumber
          postingType: postingType
        attributes:
        - name: name
          validity:
            from: 2000-01-23T04:56:07.000+00:00
            to: 2000-01-23T04:56:07.000+00:00
          value: value
        - name: name
          validity:
            from: 2000-01-23T04:56:07.000+00:00
            to: 2000-01-23T04:56:07.000+00:00
          value: value
      properties:
        ids:
          description: "\nArray of identifiers. This should contain as much information\
            \ as possible in on-boarding in order to facilitate automatic matching\
            \ where possible.\nPossible namespaces include\n- ESR:<trustId>:StaffNumber\
            \ - The staff number (Where ESR is the system of record, and <trustId>\
            \ is the Allocate Identifier for the trust)\n- NI  - the UK National Insurance\
            \ number\n- SSN - Social Security \n"
          items:
            $ref: '#/components/schemas/Identifier'
          type: array
        identification:
          $ref: '#/components/schemas/Identification'
        personalInfo:
          $ref: '#/components/schemas/PersonalInfo'
        employmentDetails:
          $ref: '#/components/schemas/EmploymentDetails'
        workLocations:
          $ref: '#/components/schemas/WorkLocations'
        postings:
          items:
            $ref: '#/components/schemas/Posting'
          type: array
        contracts:
          items:
            $ref: '#/components/schemas/Contract'
          type: array
        skills:
          items:
            $ref: '#/components/schemas/Skill'
          type: array
        specialties:
          items:
            $ref: '#/components/schemas/Specialty'
          type: array
        attributes:
          items:
            $ref: '#/components/schemas/Attribute'
          type: array
        visas:
          items:
            $ref: '#/components/schemas/Visa'
          type: array
        workingRestrictions:
          items:
            $ref: '#/components/schemas/WorkingRestriction'
          type: array
        availabilities:
          $ref: '#/components/schemas/Availabilities'
        personalPattern:
          $ref: '#/components/schemas/PersonalPattern'
      type: object
    Identification:
      description: Personally Identifiable Information
      example:
        middleInitials: middleInitials
        gender: male
        surname: Smith
        knownAs: knownAs
        dateOfBirth: 2000-01-23
        title: Mr
        forenames: '[''Fred'',''Jim'']'
      properties:
        title:
          example: Mr
          type: string
        forenames:
          description: List of forenames for the person
          example: '[''Fred'',''Jim'']'
          items: {}
          type: array
        surname:
          description: Surname for the person
          example: Smith
          type: string
        middleInitials:
          description: Any middle initials
          type: string
        knownAs:
          description: Any preferred name
          type: string
        gender:
          description: Gender if known
          enum:
          - male
          - female
          - other
          type: string
        dateOfBirth:
          format: date
          type: string
      required:
      - dateOfBirth
      - forenames
      - surname
      type: object
    PersonalPattern:
      example:
        duty:
        - '{}'
        - '{}'
        unavailability:
        - '{}'
        - '{}'
      properties:
        duty:
          items:
            properties:
              shiftGroup:
                type: string
              shift:
                type: string
              rosterLocation:
                type: string
              team:
                type: string
              activityCategory:
                type: string
              activityBenchmark:
                type: string
              activityType:
                type: string
              activityProfile:
                type: string
              work:
                type: string
              start:
                type: string
              end:
                type: string
              monthlyReccurrance:
                type: boolean
          properties:
            shiftGroup:
              type: string
            shift:
              type: string
            rosterLocation:
              type: string
            team:
              type: string
            activityCategory:
              type: string
            activityBenchmark:
              type: string
            activityType:
              type: string
            activityProfile:
              type: string
            work:
              type: string
            start:
              type: string
            end:
              type: string
            monthlyReccurrance:
              type: boolean
          type: array
        unavailability:
          items:
            properties:
              unavailabilityGroup:
                type: string
              unavailabilityReason:
                type: string
              work:
                type: string
              start:
                type: string
              end:
                type: string
              externalUnavailabilityIdentifier:
                type: string
            required:
            - end
            - externalUnavailabilityIdentifier
            - start
            - unavailabilityReason
          properties:
            unavailabilityGroup:
              type: string
            unavailabilityReason:
              type: string
            work:
              type: string
            start:
              type: string
            end:
              type: string
            externalUnavailabilityIdentifier:
              type: string
          required:
          - end
          - externalUnavailabilityIdentifier
          - start
          - unavailabilityReason
          type: array
      type: object
    WorkLocations:
      example:
        homeTrust: homeTrust
        workingTrusts:
        - ""
        - ""
      properties:
        homeTrust:
          description: The identifier for the home trust for this worker
          type: string
        workingTrusts:
          description: Identifiers for the trusts that the worker may work in (in
            addition to their home trust)
          items: {}
          type: array
      required:
      - homeTrust
      type: object
    PersonalInfo:
      example:
        additionalID: additionalID
        placeOfBirth: placeOfBirth
        nationality: nationality
        visaRequired: visaRequired
        disability: disability
        maidenName: maidenName
        ethnicOrigin: ethnicOrigin
        disabledNo: disabledNo
        maritalStatus: maritalStatus
      properties:
        maidenName:
          type: string
        maritalStatus:
          type: string
        additionalID:
          type: string
        placeOfBirth:
          type: string
        nationality:
          type: string
        ethnicOrigin:
          type: string
        visaRequired:
          type: string
        disabledNo:
          type: string
        disability:
          type: string
      type: object
    EmploymentDetails:
      example:
        employeeType: employeeType
        dateJoinedNHS: dateJoinedNHS
        hireDetails: hireDetails
        agencies: agencies
        employmentStatus: employmentStatus
        prevEmployer: prevEmployer
        alAccrualPlan: alAccrualPlan
      properties:
        employmentStatus:
          type: string
        employeeType:
          type: string
        hireDetails:
          type: string
        dateJoinedNHS:
          type: string
        alAccrualPlan:
          type: string
        prevEmployer:
          type: string
        agencies:
          type: string
      required:
      - hireDetails
      type: object
    Posting:
      example:
        unit: unit
        post: post
        isPrimary: true
        team: team
        assignmentNumber: assignmentNumber
        postingType: postingType
      properties:
        unit:
          type: string
        post:
          type: string
        postingType:
          type: string
        assignmentNumber:
          type: string
        team:
          type: string
        isPrimary:
          type: boolean
      required:
      - assignmentNumber
      - isPrimary
      - unit
      type: object
    Contract:
      example:
        wtdOptOut: true
        salaryAmount: 0.8008281904610115
        staffGroup: staffGroup
        contractType: contractType
        salaryFrequency: salaryFrequency
        grade: grade
        contract: contract
        contractedTime: contractedTime
        defaultUnavailabilityHours: defaultUnavailabilityHours
        payscale: payscale
      properties:
        staffGroup:
          type: string
        grade:
          type: string
        contract:
          type: string
        payscale:
          type: string
        contractType:
          type: string
        contractedTime:
          type: string
        defaultUnavailabilityHours:
          type: string
        wtdOptOut:
          type: boolean
        salaryFrequency:
          type: string
        salaryAmount:
          type: number
      required:
      - contract
      - contractedTime
      - grade
      type: object
    Skill:
      example:
        skillGroup: skillGroup
        dateGained: dateGained
        cluster: cluster
        notes: notes
        obtainedFromReason: obtainedFromReason
        certificateNumber: certificateNumber
        skill: skill
        validity:
          from: 2000-01-23T04:56:07.000+00:00
          to: 2000-01-23T04:56:07.000+00:00
      properties:
        skillGroup:
          type: string
        cluster:
          type: string
        skill:
          type: string
        validity:
          $ref: '#/components/schemas/DateSpan'
        dateGained:
          type: string
        obtainedFromReason:
          type: string
        certificateNumber:
          type: string
        notes:
          type: string
      required:
      - validity
      type: object
    Specialty:
      example:
        notes: notes
        validity:
          from: 2000-01-23T04:56:07.000+00:00
          to: 2000-01-23T04:56:07.000+00:00
        tempStaffSpeciality: tempStaffSpeciality
      properties:
        tempStaffSpeciality:
          type: string
        validity:
          $ref: '#/components/schemas/DateSpan'
        notes:
          type: string
      required:
      - validity
      type: object
    Attribute:
      example:
        name: name
        validity:
          from: 2000-01-23T04:56:07.000+00:00
          to: 2000-01-23T04:56:07.000+00:00
        value: value
      properties:
        validity:
          $ref: '#/components/schemas/DateSpan'
        name:
          type: string
        value:
          type: string
      required:
      - name
      - validity
      - value
      type: object
    Visa:
      example:
        number: number
        country: country
        entries: entries
        issuingOffice: issuingOffice
        validity:
          from: 2000-01-23T04:56:07.000+00:00
          to: 2000-01-23T04:56:07.000+00:00
        type: type
      properties:
        number:
          type: string
        country:
          type: string
        issuingOffice:
          type: string
        type:
          type: string
        entries:
          type: string
        validity:
          $ref: '#/components/schemas/DateSpan'
      required:
      - validity
      type: object
    WorkingRestriction:
      example:
        hoursOfWork:
          thu:
            from: 01:00
            to: 08:30
          tue:
            from: 01:00
            to: 08:30
          wed:
            from: 01:00
            to: 08:30
          sat:
            from: 01:00
            to: 08:30
          fri:
            from: 01:00
            to: 08:30
          mon:
            from: 01:00
            to: 08:30
          sun:
            from: 01:00
            to: 08:30
        restrictions:
          maxConsecutiveDaysRequested: maxConsecutiveDaysRequested
          maxOvertimePerWeek: maxOvertimePerWeek
          minBreakBetweenShifts: 6.027456183070403
          notes: notes
          wtdWeekTimeStart: wtdWeekTimeStart
          additionalHoursPerWeek: additionalHoursPerWeek
          maxConsecutiveDays: maxConsecutiveDays
          maxOvertimePerDay: maxOvertimePerDay
          wtdWeekDayStart: wtdWeekDayStart
          maxShiftsPerWeek: maxShiftsPerWeek
          wtdDayStart: wtdDayStart
          maxDurationPerShift: maxDurationPerShift
          maxOvertimePerCalendarMonth: maxOvertimePerCalendarMonth
          effectiveFrom: effectiveFrom
          maxWorkTimePerDay: maxWorkTimePerDay
          daysPerWeek: daysPerWeek
          maxDaysPerWeek: maxDaysPerWeek
        validity:
          from: 2000-01-23T04:56:07.000+00:00
          to: 2000-01-23T04:56:07.000+00:00
        title: title
        defaultLeaveHours:
          fridayTime: fridayTime
          useWorkingDay: useWorkingDay
          tuesdayTime: tuesdayTime
          mondayTime: mondayTime
          sundayTime: sundayTime
          saturdayTime: saturdayTime
          wednesdayTime: wednesdayTime
      properties:
        title:
          type: string
        validity:
          $ref: '#/components/schemas/DateSpan'
        hoursOfWork:
          $ref: '#/components/schemas/WorkingRestriction_hoursOfWork'
        defaultLeaveHours:
          $ref: '#/components/schemas/WorkingRestriction_defaultLeaveHours'
        restrictions:
          $ref: '#/components/schemas/WorkingRestriction_restrictions'
      required:
      - defaultLeaveHours
      - hoursOfWork
      - restrictions
      - title
      - validity
      type: object
    Availabilities:
      example:
        Availability:
        - '{}'
        - '{}'
        NoBank:
        - '{}'
        - '{}'
      properties:
        Availability:
          items:
            properties:
              date:
                type: string
              availabilityType:
                type: string
              start:
                type: string
              end:
                type: string
              doubleOfOccurrences:
                type: number
              notes:
                type: string
          properties:
            date:
              type: string
            availabilityType:
              type: string
            start:
              type: string
            end:
              type: string
            doubleOfOccurrences:
              type: number
            notes:
              type: string
          type: array
        NoBank:
          items:
            properties:
              start:
                type: string
              doubleOfOccurances:
                type: number
              notes:
                type: string
          properties:
            start:
              type: string
            doubleOfOccurances:
              type: number
            notes:
              type: string
          type: array
      required:
      - Availability
      - NoBank
      type: object
    WorkerRegistrationResponse:
      example:
        workerId: 3B78B5C3-07B3-4DC6-8A2A-7D85153869FC
      properties:
        workerId:
          description: Allocate Worker ID of the person
          example: 3B78B5C3-07B3-4DC6-8A2A-7D85153869FC
          type: string
      required:
      - workerId
      type: object
    inline_object:
      properties:
        trustCode:
          description: The code for the trust that the worker should be on-boarded
            to
          type: string
        engagementRoute:
          description: The 'engagement route' of the worker, such as substantive,
            bank, agency
          type: string
      type: object
    WorkingRestriction_hoursOfWork:
      example:
        thu:
          from: 01:00
          to: 08:30
        tue:
          from: 01:00
          to: 08:30
        wed:
          from: 01:00
          to: 08:30
        sat:
          from: 01:00
          to: 08:30
        fri:
          from: 01:00
          to: 08:30
        mon:
          from: 01:00
          to: 08:30
        sun:
          from: 01:00
          to: 08:30
      properties:
        mon:
          $ref: '#/components/schemas/TimeSpan'
        tue:
          $ref: '#/components/schemas/TimeSpan'
        wed:
          $ref: '#/components/schemas/TimeSpan'
        thu:
          $ref: '#/components/schemas/TimeSpan'
        fri:
          $ref: '#/components/schemas/TimeSpan'
        sat:
          $ref: '#/components/schemas/TimeSpan'
        sun:
          $ref: '#/components/schemas/TimeSpan'
    WorkingRestriction_defaultLeaveHours:
      example:
        fridayTime: fridayTime
        useWorkingDay: useWorkingDay
        tuesdayTime: tuesdayTime
        mondayTime: mondayTime
        sundayTime: sundayTime
        saturdayTime: saturdayTime
        wednesdayTime: wednesdayTime
      properties:
        useWorkingDay:
          type: string
        mondayTime:
          type: string
        tuesdayTime:
          type: string
        wednesdayTime:
          type: string
        fridayTime:
          type: string
        saturdayTime:
          type: string
        sundayTime:
          type: string
    WorkingRestriction_restrictions:
      example:
        maxConsecutiveDaysRequested: maxConsecutiveDaysRequested
        maxOvertimePerWeek: maxOvertimePerWeek
        minBreakBetweenShifts: 6.027456183070403
        notes: notes
        wtdWeekTimeStart: wtdWeekTimeStart
        additionalHoursPerWeek: additionalHoursPerWeek
        maxConsecutiveDays: maxConsecutiveDays
        maxOvertimePerDay: maxOvertimePerDay
        wtdWeekDayStart: wtdWeekDayStart
        maxShiftsPerWeek: maxShiftsPerWeek
        wtdDayStart: wtdDayStart
        maxDurationPerShift: maxDurationPerShift
        maxOvertimePerCalendarMonth: maxOvertimePerCalendarMonth
        effectiveFrom: effectiveFrom
        maxWorkTimePerDay: maxWorkTimePerDay
        daysPerWeek: daysPerWeek
        maxDaysPerWeek: maxDaysPerWeek
      properties:
        effectiveFrom:
          type: string
        daysPerWeek:
          type: string
        maxDaysPerWeek:
          type: string
        maxShiftsPerWeek:
          type: string
        maxConsecutiveDays:
          type: string
        maxConsecutiveDaysRequested:
          type: string
        maxWorkTimePerDay:
          type: string
        maxDurationPerShift:
          type: string
        additionalHoursPerWeek:
          type: string
        maxOvertimePerDay:
          type: string
        maxOvertimePerWeek:
          type: string
        maxOvertimePerCalendarMonth:
          type: string
        wtdDayStart:
          type: string
        wtdWeekDayStart:
          type: string
        wtdWeekTimeStart:
          type: string
        minBreakBetweenShifts:
          type: number
        notes:
          type: string
  securitySchemes:
    jwt:
      bearerFormat: JWT
      description: JSON Web Token previously obtained from the Allocate authentication
        server
      scheme: bearer
      type: http
      x-bearerInfoFunc: api_server.controllers.security_controller_.info_from_jwt
    APIAuthorizer:
      in: header
      name: AuthorizationToken
      type: apiKey
      x-amazon-apigateway-authtype: custom
      x-amazon-apigateway-authorizer:
        authorizerUri: arn:aws:apigateway:eu-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-2:529795807852:function:lambda_interop_auth/invocations
        authorizerCredentials: arn:aws:iam::529795807852:role/iam_for_lambda
        authorizerResultTtlInSeconds: 300
        type: token
      x-apikeyInfoFunc: api_server.controllers.security_controller_.info_from_APIAuthorizer
